version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: case_study_backend
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: .
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: case_study_backend
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      AI_FALLBACK_TO_MOCK: 1
    ports:
      - "3000:3000"
    restart: unless-stopped
volumes:
  mysql_data:
