name: Build Submission PDF

on:
  push:
    paths:
      - "SUBMISSION.md"
      - ".github/workflows/submission-pdf.yml"
    branches: [main]
  workflow_dispatch: {}

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare output dir
        run: mkdir -p dist

      - name: Build PDF (pandoc/latex Docker image)
        run: |
          docker run --rm -v "${{ github.workspace }}":/data pandoc/latex:latest \
            SUBMISSION.md \
            -o dist/submission.pdf \
            --from gfm \
            --metadata=title:"AI CV Evaluator Submission" \
            --toc \
            --pdf-engine=xelatex

      - name: List output
        run: ls -l dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: submission-pdf
          path: dist/submission.pdf
          if-no-files-found: error

      - name: Summary
        run: echo 'PDF built via pandoc/latex Docker image and uploaded.' >> $GITHUB_STEP_SUMMARY
